package io.testproject.generated.tests.myfirstproject;

import io.testproject.java.annotations.v2.Parameter;
import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.ParameterDirection;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.AndroidDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.AndroidTest;
import io.testproject.java.sdk.v2.tests.helpers.AndroidTestHelper;
import java.lang.String;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: My first Project
 * Test: PruebaErrorDiegoPerez
 * Generated by: ツ Fake Feelings † (diegochino1311@gmail.com)
 * Generated on Thu Jul 07 06:32:34 GMT 2022.
 */
@Test(
    name = "PruebaErrorDiegoPerez",
    version = "1.0"
)
public class Pruebaerrordiegoperez implements AndroidTest {
  @Parameter(
      defaultValue = "No se puede dividir",
      direction = ParameterDirection.INPUT
  )
  public String Error;

  public ExecutionResult execute(AndroidTestHelper helper) throws FailureException {
    AndroidDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    boolean booleanResult;

    // 1. Reset App
    //    Clear application data and restart (Auto-generated)
    GeneratedUtils.sleep(500);
    booleanResult = driver.testproject().resetApp();
    report.step("Reset App", booleanResult, TakeScreenshotConditionType.Failure);

    // 2. Click '9'
    GeneratedUtils.sleep(500);
    by = By.id("com.miui.calculator:id/btn_9_s");
    booleanResult = driver.testproject().click(by);
    report.step("Click '9'", booleanResult, TakeScreenshotConditionType.Failure);

    // 3. Click '9'
    GeneratedUtils.sleep(500);
    by = By.id("com.miui.calculator:id/btn_9_s");
    booleanResult = driver.testproject().click(by);
    report.step("Click '9'", booleanResult, TakeScreenshotConditionType.Failure);

    // 4. Click 'dividir'
    GeneratedUtils.sleep(500);
    by = By.id("com.miui.calculator:id/btn_div_s");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'dividir'", booleanResult, TakeScreenshotConditionType.Failure);

    // 5. Click '0'
    GeneratedUtils.sleep(500);
    by = By.id("com.miui.calculator:id/btn_0_s");
    booleanResult = driver.testproject().click(by);
    report.step("Click '0'", booleanResult, TakeScreenshotConditionType.Failure);

    // 6. Does 'igual a' contain '[NONE]'?
    GeneratedUtils.sleep(500);
    by = By.id("com.miui.calculator:id/btn_equal_s");
    booleanResult = driver.testproject().containsText(by,"");
    report.step("Does 'igual a' contain '[NONE]'?", booleanResult, TakeScreenshotConditionType.Failure);

    // 7. Is '= No se puede dividir entre cer' not present or invisible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//android.widget.ListView/android.widget.LinearLayout[2]/android.widget.TextView[@checked = 'false']");
    // Unable to generate code for the step index 7// 8. Is '= No se puede dividir entre cer' not present or invisible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//android.widget.ListView/android.widget.LinearLayout[2]/android.widget.TextView[@checked = 'false']");
    // Unable to generate code for the step index 8return ExecutionResult.PASSED;
  }
}
